# Menus
menu:
  主页: .
  关于: about

# Customize
customize:
  logo:
    enabled: true
    width: 40
    height: 40
    url: /images/avatar.png
  profile:
    enabled: true # Whether to show profile bar
    avatar: images/avatar.png
    gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: Problem233
    author_title: 编程/游戏/电音
    location: 中国 浙江
    follow: https://github.com/problem233/
  highlight: solarized-dark
  sidebar: right # sidebar position, options: left, right or leave it empty
  thumbnail: true # enable posts thumbnail, options: true, false
  favicon: images/favicon.ico # path to favicon
  social_links:
    github: https://github.com/Problem233
    twitter: https://twitter.com/problem_233
    weibo: http://weibo.com/228521472
    rss: https://problem233.github.io/atom.xml
  social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
  - recent_posts
  - tagcloud
  - archive
  - links

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
  disqus: # enter disqus shortname here
  duoshuo: # enter duoshuo shortname here
  youyan: # enter youyan uid here
  facebook: # enter true to enable
  isso: # enter the domain name of your own comment isso server eg. comments.example.com
  changyan: # please fill in `appid` and `conf` to enable
    appid:
    conf:
  gitment:
    owner: problem233 #your github ID
    repo: blog #the repo to store comments
    # Register an OAuth application, and you will get a client ID and a client secret.
    client_id: a48a630b374fd9dc34bd #your client ID
    client_secret: 99c7771a8a360bcbd42f64e91ccc162dffc03962 #your client secret

# Share
share: addtoany # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
  lightgallery: true # options: true, false
  justifiedgallery: true # options: true, false
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  mathjax: true # options: true, false

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
  links:
    光丝图谱: /silk/
    Simulation the world in emoji: /simulation/model/
    Hexo: http://hexo.io
    SW_Wind: https://swwind.github.io/
    某 Frank 污: https://frankfoot.github.io/
